baseURL: "https://aissa-abdelaziz.netlify.app/"
languageCode: "en-us"
title: "Aissa ABDELAZIZ"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
 # main:
    #- identifier: blog
    # name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Aissa ABDELAZIZ"
  description: Hi there! I'm Aissa, a passionate Computer Vision and AI student. Dive into my portfolio to discover my professional journey, academic background, innovative projects, and technical skills.
  

  # staticPath: ""  # The path to serve the static files from
  favicon: "/image_circle.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Welcome to my portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Aissa ."
    subtitle: "Copmuter Vision and AI Enthusiast 👨‍💻"
    content: |
      I am a passionate student specializing in Computer Vision and AI, currently pursuing the Master MVA : Mathematics, Vision, and AI at ENS Paris-Saclay 🎓.

      📧 Email: aissa.abdelaziz@ens-paris-saclay.fr  
      📍 Based in Paris, France 🇫🇷
    image: /images/aissa_style3.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1tPUowrWU2Bie2PamcsU4vIu9ao-SA9RQ/view?usp=sharing"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/aissa-abdelaziz
        - icon: fab fa-x-twitter
          url: https://x.com/AbdelazizAisaa?t=vDI-79BNvYiHdtduYuQLTg&s=09
        - icon: fa-brands fa-linkedin
          url: https://www.linkedin.com/in/aissa-abdelaziz-50b8b819b/

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I am a Master's student in AI and Computer Vision with a solid background in machine learning and deep learning. Passionate about solving complex problems and building AI models, I bring a versatile engineering skill set. Motivated, hardworking, and eager to learn, I am dedicated to advancing in the field of AI. 

      I am currently doing my final year internship as a Software Engineer in Computer Vision at GoPro 📷 in Paris 🇫🇷, where I am working on Video Frame Interpolation (VFI) 🎥.    
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Pytorch"
        - "Docker"
        - "Git"
        - "Google Cloud"
        - "Amazon SageMaker"
        - "Qualcomm AI Hub" 


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master 2 MVA: Mathematics, Vision, AI"
        school:
          name: "Ecole Normale Supérieure Paris-Saclay"
          url: "https://www.master-mva.com/"
        date: "2023 - 2024"
        GPA: "4 out of 4"
        content: |-
          Relevant Courses:
            - Object Recognition and Computer Vision, Deep Learning in Practice, Probabilistic Graphical
              Models and Deep Generative Models, Bayesian Machine Learning, Deep Learning for Medical Imaging, Learning
              and Generation by Sampling Probabilities, Deep Learning for Signal Processing, Reproducible Research Project 
      - title: "Master 1 Computer Vision and Robotics"
        school:
          name: "Université Paris-Saclay"
          url: "https://www.universite-paris-saclay.fr/en"
        date: "2022 - 2023"
        GPA: "3.5 out of 4"
        content: |-
          Relevant Courses:
          - Machine Vision, Machine Learning, Algorithms with Python, Embedded Systems, Image
            Processing, Signal Processing, Robotics, Advanced Control Systems 

      - title: "Bachelor in Electronics and Computer Engineering"
        school:
          name: "Institute of Electrical and Electronic Engineering (IGEE) of Algeria"
          url: "https://igee.univ-boumerdes.dz/Graduation.html"
        date: "2019 - 2022"
        GPA: "3.5 out of 4 (Ranking: Top 3%)"
        content: |-
          Relevant Courses:
          - Computer Architecture, Programming in C, Digital Systems with VHDL, Linear Algebra,
          Physics, Electronics, Telecommunications, Automation


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Computer Vision Intern"
        company: "GoPro"
        companyUrl: "https://gopro.com/fr/fr/"
        date: "April 2024 - present"
        info:
          enable: true
          content: I worked as a computer vision intern on the VFI project.
        content: |
          I worked on the Video Frame Interpolation (VFI) project:
            - Supported the productionization of Video Frame Interpolation (VFI) algorithms for inference on edge devices.
            - Conducted research and analysis to curate a list of top State-of-the-Art (SOTA) candidates ranked by feasibility to be deployed at the edge, based on speed, quality, and memory consumption.
            - Transformed selected models into formats optimized for edge deployment and ensured compatibility and efficiency.
      - job: "Data Science Intern"
        company: "Assystem"
        companyUrl: "https://www.assystem.com/fr/"
        date: "June 2023 – August 2023"
        info:
          enable: true
          content: I worked as a Data Science intern on table detection in documents.
        content: |
          I worked on complicated table detection in documents:
            - Conducted a comprehensive review of state-of-the-art methodologies in deep learning to extract tabular data efficiently.
            - Collected and preprocessed a tabular dataset to be utilized for model training, ensuring data quality and integrity.
            - Trained and evaluated the selected graph-based learning model, with a focus on performance optimization and scalability.



  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Image Matting Using A Closed Form Solution
        content: Accurately estimates foreground objects in images, based on local smoothness assumptions regarding foreground and background colors, known as the color-line model.
        image: /images/projects/image_matting.jpg 
        featured:
          name: Demo
          link: https://ipolcore.ipol.im/demo/clientApp/demo.html?id=532
        badges:
          - "IPOL"
          - "Python"
          - "Docker"
        links:
          - icon: fab fa-github
            url: https://github.com/reproductible-research/image-matting-with-a-closed-form-solution
          - icon: fab fa-researchgate
            url: https://www.ipol.im/pub/pre/532/

      - title: Sign Language Translation
        content: Training the multimodal transformer model to translate sign language videos into text . 
        image: /images/projects/SLT.png
        badges:
          - "Pytorch"
          - "Google Cloud"
        links:
          - icon: fab fa-github
            url: https://github.com/aissa-abdelaziz/Sign-Language-Translation

      - title: Bayesian Image Super-Resolution
        content: Super-Resolution approach from a Bayesian perspective by estimating the unknown point spread function.
        image: /images/projects/sr_image.jpg
        badges:
          - "Pytorch"
          - "Bayesian ML"
        links:
          - icon: fab fa-github
            url: https://github.com/aissa-abdelaziz/Bayesian-Image-Super-Resolution

      - title: Capturing Label Characteristics in VAE
        content: Develop and train a CCVAE model that integrates labels into VAEs, thereby enhancing its capability to capture rich characteristics associated with those labels.
        image: /images/projects/ccvae.png
        badges:
          - "Pytorch"
          - "VAE"
        links:
          - icon: fab fa-github
            url: https://github.com/aissa-abdelaziz/Bayesian-Image-Super-Resolution

      - title: Data Augmentation Using GANs for Classification Task
        content: Develop a DCGAN to generate new images of 3D animals (Cows and Horses) to be added to the original dataset to train a CNN classifier . 
        image: /images/projects/ccvae.png
        badges:
          - "Pytorch"
          - "GAN"
        links:
          - icon: fab fa-github
            url: https://github.com/aissa-abdelaziz/Bayesian-Image-Super-Resolution

  # Contact
  contact:
    enable: true
    title: "Contact"
    content: |
      Have something cool to discuss or just want to say hey? I'm all ears!

    btnName: Let's Connect
    btnLink: mailto:abdelazizaissa2002@gmail.com
    formspree:
      enable: true
      formId: xdoqqzqq
      emailCaption: "Your Email"
      messageCaption: "Drop Me a Line"


  footer:


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Aissa ABDELAZIZ"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
